version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly" # Checks every week
    reviewers:
      - "arfshl"
    groups:
      github-actions-updates:
        patterns:
          - "*" # Groups all action updates into one PR
